version: '3.8'

services:
  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}

  backend:
    build: backend
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database

networks:
  db: