version: '3.8'

services:
  backend:
    build: backend
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
