version: '3.8'

services:
  redisdb:
    image: redis:7.2-rc2-alpine3.18
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - redisnetwork
  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - db

  backend:
    image: backend
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    restart: on-failure
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file: .env
    depends_on:
      - database
      - redisdb
    networks:
      - db
      - redisnetwork
    volumes:
      - backend-shared-volume:/app/packages/service-backend/
    healthcheck:
      test: curl -s -f http://localhost:${BACKEND_PORT}/health || /bin/bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 1.5s

  prismastudio:
    image: backend_prisma_studio
    build: backend
    command: yarn prisma studio
    restart: always
    ports:
      - ${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}
    depends_on:
      - backend
    networks:
      - db

networks:
  db:
  redisnetwork:


volumes:
  backend-shared-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./packages/service-backend/