parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:storybook/recommended

settings:
  import/resolver:
    typescript: {}

plugins:
  - import
  - react
  - react-hooks
  - prettier
  - simple-import-sort

ignorePatterns: ["vite.config.ts", "cypress.config.ts"]

rules:
  prettier/prettier: warn

  react/react-in-jsx-scope: 0
  react/no-unescaped-entities: 0
  react/jsx-props-no-spreading: 0
  react/require-default-props: 0
  react/no-children-prop: 0

  no-alert: 0
  no-console: 0
  no-param-reassign: ["error", { props: true, ignorePropertyModificationsFor: ["state"] }]
  no-nested-ternary: 0

  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/ban-ts-comment": off

  "simple-import-sort/imports": [
    "warn", {
      "groups": [
        ["^react", "^@?\\w"],
        # all folders in src
        ["^(src)(/.*|$)"],
        ["^\\u0000"],
        ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
        ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
        ["^.+\\.?(css)$"]
      ]
    }
  ]
  "simple-import-sort/exports": 1

  import/prefer-default-export: 0