FROM node:18.16.0

WORKDIR /app

COPY ./packages/service-backend/package.json ./package.json ./yarn.lock ./

RUN yarn set version stable && echo "\nnodeLinker: node-modules" >> .yarnrc.yml

WORKDIR /app/packages/service-backend

RUN yarn install

RUN yarn dlx prisma

WORKDIR /app

COPY . .

RUN yarn install

WORKDIR /app/packages/service-backend

RUN yarn prisma generate

RUN yarn build

CMD yarn start:prod
