FROM node:alpine

WORKDIR /app

RUN yarn global add typescript

COPY . .

RUN yarn install

RUN cd packages/service-backend && npx prisma generate --schema=./prisma/schema.prisma

CMD [ "yarn", "start:dev" ]