name: Build & Start Backend

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build backend container
        id: build
        run: docker compose build backend

      - name: Run backend container
        id: run
        run: docker compose up -d backend

      - name: Stop backend container
        id: stop
        run: docker compose down

