name: Build, Start and Stop Backend Container

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
      - development

jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    environment: Docker
    env:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PRISMA_STUDIO_PORT: ${{ secrets.PRISMA_STUDIO_PORT }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
      FRONTEND_URL: "http://localhost:3000"
      FRONTEND_PORT: "3000"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build Ollamy base
        id: build-ollamy-base
        run: cd dockerfiles/base && ./build.sh

      - name: Build backend container
        id: build
        run: docker compose build backend

      - name: Run backend container
        id: run
        run: docker compose up --wait -d backend

      - name: Check OpenApi generation
        id: check
        run: ./script/openapi/test-backend-client-generator-cli.sh http://localhost:${{ secrets.BACKEND_PORT }} packages/service-maker script/openapi

      - name: Run backend tests
        id: test
        run: docker-compose exec -it backend yarn test:cov:json

      - name: Create test-reports directory
        id: create-directory
        run: mkdir -p test-reports

      - name: Copy coverage report to test-reports directory
        id: copy-coverage-report
        run: docker cp "$(docker-compose ps -q backend)":/app/packages/service-backend/coverage/coverage.json test-reports/

      - name: Stop backend container
        id: stop
        run: docker compose down
