name: Deploy test version

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'Deploy-test-version' }}
    runs-on: ubuntu-latest
    environment: Docker

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd ollamy-deploy
          git checkout ${{ github.head_ref || github.ref_name }} && git pull origin ${{ github.head_ref || github.ref_name }}
          sed -i 's/REDIS_PORT=6379/REDIS_PORT=6380/g' .env
          sed -i 's/POSTGRES_PORT=5432/POSTGRES_PORT=5433/g' .env
          sed -i 's/BACKEND_PORT=3000/BACKEND_PORT=4545/g' .env
          source .env
          docker compose build backend
          docker compose up -d backend
          docker exec ollamy-deploy-backend-1 yarn prisma migrate reset "--force"


    - name: send PR comment
      uses: mshick/add-pr-comment@v2
      if: ${{ success() }}
      with:
        message-id: deploy-test-version
        message: |
          The deployment was successful! 🚀🚀🚀
          The backend test version is now available at: http://${{ secrets.REMOTE_HOST }}:4545/api
          🛑🛑 The server will be stopped in 10 minutes. 🛑🛑

    - name: STOP the Staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd ollamy-deploy
          sleep 600
          docker compose stop backend redis database || true
          echo "The server has been stopped. cleanup completed."
