name: Deploy test version

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'Deploy-test-version' }}
    runs-on: ubuntu-latest
    environment: Docker

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd ollamy-deploy
          git checkout development && git pull origin development
