name: Lint - Mobile application

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
      - development
    paths:
      - packages/service-mobile-app/**

jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    environment: Docker
    env:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PRISMA_STUDIO_PORT: ${{ secrets.PRISMA_STUDIO_PORT }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        id: install
        run: cd packages/service-mobile-app && yarn install

      - name: Lint
        id: lint
        run: cd packages/service-mobile-app && yarn lint
